format = """
[  ](fg:#090c0c bg:#a3aed2 )\
[](fg:#a3aed2 bg:#769ff0)\
$directory\
[](fg:#769ff0 bg:#1d2230)\
$git_branch\
$git_status\
[ ](fg:#1d2230)\
$fill \
$python\
$golang\
$kubernetes\
\n$character
"""

# right_format = """$python"""

[fill]
symbol = " "

[directory]
style = "fg:#1d2230 bg:#769ff0"
format = "[ $path ]($style)"
truncate_to_repo = true
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~/work/" = " "

[kubernetes]
style = "fg:#769ff0 bg:#1d2230"
disabled = false
detect_files = ["k8s"]
format = '[](fg:#1d2230)[${symbol} ($user on )$context \($namespace\)]($style) '
[kubernetes.context_aliases]
"minikube" = "dev"
"arn:aws:eks:us-west-1:976748715263:cluster/uxi_staging" = "uxi_staging"
[kubernetes.user_aliases]
"minikube" = "dev"
"arn:aws:eks:us-west-1:976748715263:cluster/uxi_staging" = "dev"


[python]
style = "fg:#769ff0 bg:#1d2230"
pyenv_version_name = false
format = "[](fg:#1d2230)[${symbol} ${version}]($style)"
disabled = false

[golang]
style = "fg:#769ff0 bg:#1d2230"
format = "[](fg:#1d2230)[${symbol} ${version}]($style)"
disabled = false

[git_branch]
symbol = ""
style = "bg:#1d2230"
format = '[[ $symbol ](fg:#769ff0 bg:#1d2230)]($style)'

[git_status]
style = "bg:#1d2230"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '[[($all_status $ahead_behind)](fg:#769ff0 bg:#1d2230)]($style)'
