format = """
[ \uf313 ](fg:#268bd2 bg:#002b36)\
[\ue0b0](fg:#002b36 bg:#073642)\
$directory\
[\ue0b0](fg:#073642 bg:#002b36)\
$git_branch\
$git_status\
[\ue0b0 ](fg:#002b36)\
$character
"""

right_format = """$python$golang$kubernetes"""

[fill]
symbol = " "

[directory]
style = "fg:214 bg:#073642"
format = "[ $path ]($style)"
truncate_to_repo = true
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~/work/" = " "

[kubernetes]
style = "fg:green bg:#1d2230"
disabled = false
detect_files = ["k8s"]
format = "[\ue0b2](fg:#1d2230)[${symbol} ($user on )$context ($namespace)]($style)"

[kubernetes.context_aliases]
"minikube" = "dev"
"arn:aws:eks:us-west-1:976748715263:cluster/uxi_staging" = "uxi_staging"

[kubernetes.user_aliases]
"minikube" = "dev"
"arn:aws:eks:us-west-1:976748715263:cluster/uxi_staging" = "dev"


[python]
style = "fg:green bg:#1d2230"
pyenv_version_name = false
format = "[\ue0b2](fg:#1d2230)[${symbol} ${version}]($style)"
disabled = false

[golang]
style = "fg:green bg:#1d2230"
format = "[\ue0b2](fg:#1d2230)[${symbol} ${version}]($style)"
disabled = false

[git_branch]
symbol = ""
style = "bg:#002b36"
format = '[[ $symbol ](fg:#eee8d5 bg:#002b36)]($style)'

[git_status]
style = "bg:#002b36"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
format = '[[($all_status $ahead_behind)](fg:red bg:#002b36)]($style)'
